import { FitnessPlan } from '../types/fitness';

export const initialFitnessPlan: FitnessPlan = {
  id: 'starter-plan-1',
  title: 'FitBuddy Foundation: Total Body Strength & Metabolic Conditioning',
  overview: 'A balanced 4-day hybrid training program engineered for fat loss, core stability, and functional muscle tone.',
  targetGoal: 'general-fitness',
  workoutIntensity: 'medium',
  experienceLevel: 'beginner',
  language: 'en',
  createdAt: '2026-09-24',
  safetyNotice: 'Warm up thoroughly before loading movements. Listen to your body and execute modifications if joint pain occurs.',
  weeklyAdvice: 'Consistency beats intensity. Aim for 7-8 hours of sleep and drink 2.5 to 3 liters of water daily.',
  days: [
    {
      dayIndex: 1,
      dayName: 'Day 1: Upper Body Push & Core Stability',
      focus: 'Chest, Shoulders, Triceps, and Deep Core',
      isRestDay: false,
      estimatedMinutes: 35,
      warmup: [
        'Arm circles (forward & backward) - 30 seconds',
        'Cat-Cow spinal mobility - 10 reps',
        'Scapular wall slides - 12 reps',
      ],
      exercises: [
        {
          id: 'ex-101',
          name: 'Incline or Floor Push-Ups',
          nameTamil: 'புஷ்-அப் (மார்பு பயிற்சி)',
          targetMuscleGroup: 'Pectorals, Anterior Deltoids, Triceps',
          sets: 3,
          repsOrDuration: '8 - 12 reps',
          restSeconds: 60,
          difficulty: 'beginner',
          instructions: [
            'Place hands slightly wider than shoulder-width, fingers spread.',
            'Keep core engaged and body in a straight line from heels to head.',
            'Lower your chest until elbows are at a 45-degree angle to your torso.',
            'Press through your whole palm back to top lockout.',
          ],
          safetyCues: [
            'Do not let lower back sag or hips pike in the air.',
            'Keep neck neutral by looking a few inches ahead of hands.',
          ],
          modification: 'Perform on elevated surface (bench or kitchen counter) or from knees.',
          equipmentNeeded: 'Bodyweight',
        },
        {
          id: 'ex-102',
          name: 'Dumbbell Neutral-Grip Overhead Press',
          nameTamil: 'டம்பெல் ஷோல்டர் பிரஸ்',
          targetMuscleGroup: 'Shoulders, Triceps, Upper Chest',
          sets: 3,
          repsOrDuration: '10 - 12 reps',
          restSeconds: 60,
          difficulty: 'beginner',
          instructions: [
            'Hold dumbbells at shoulder height with palms facing each other.',
            'Brace core and glutes to avoid hyperextending the lower back.',
            'Press dumbbells smoothly straight overhead until arms are extended.',
            'Control the descent back to shoulder level over 2 seconds.',
          ],
          safetyCues: [
            'Never arch the lower back to force the weight up.',
            'Neutral grip reduces impingement pressure on the rotator cuff.',
          ],
          modification: 'Use lighter water bottles, resistance bands, or seated press.',
          equipmentNeeded: 'Dumbbells / Resistance Band',
        },
        {
          id: 'ex-103',
          name: 'Bench / Chair Tricep Dips',
          nameTamil: 'ட்ரைசெப் டிப்ஸ்',
          targetMuscleGroup: 'Triceps and Anterior Shoulder',
          sets: 3,
          repsOrDuration: '10 reps',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Sit on the edge of a sturdy chair or bench, hands next to hips.',
            'Slide hips forward just off the edge, feet flat on floor with knees bent at 90 degrees.',
            'Lower body by bending elbows until they reach about 90 degrees.',
            'Press through palms to return to starting position.',
          ],
          safetyCues: [
            'Keep your back close to the chair edge to prevent shoulder strain.',
            'Do not dip below 90 degrees at the elbows.',
          ],
          modification: 'Keep feet closer to chair for less bodyweight resistance.',
          equipmentNeeded: 'Sturdy Chair or Bench',
        },
        {
          id: 'ex-104',
          name: 'Dead Bug Core Hollow Hold',
          nameTamil: 'டெட் பக் வயிற்றுப் பயிற்சி',
          targetMuscleGroup: 'Transverse Abdominis, Deep Core',
          sets: 3,
          repsOrDuration: '8 reps per side',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Lie flat on back with arms reaching toward ceiling and knees bent at 90 degrees.',
            'Press your lower back firmly into the floor.',
            'Slowly extend right arm overhead and left leg straight out toward floor.',
            'Return to center and switch to opposite arm and leg.',
          ],
          safetyCues: [
            'If lower back arches off the floor, shorten leg extension distance.',
            'Breathe out as limbs extend.',
          ],
          modification: 'Tap heels to floor with knees bent instead of full leg extension.',
          equipmentNeeded: 'Yoga Mat / Carpet',
        },
      ],
      cooldown: [
        'Doorway chest stretch - 30 seconds per side',
        'Overhead triceps stretch - 30 seconds per arm',
        'Child’s pose - 60 seconds with deep diaphragmatic breaths',
      ],
      coachTip: 'Focus on clean controlled tempo (2 seconds down, 1 second up) rather than rushing through reps.',
    },
    {
      dayIndex: 2,
      dayName: 'Day 2: Lower Body Power & Knee Resilience',
      focus: 'Quadriceps, Glutes, Hamstrings, and Calves',
      isRestDay: false,
      estimatedMinutes: 35,
      warmup: [
        'Bodyweight air squats - 10 gentle reps',
        'Leg swings (forward & lateral) - 10 reps per leg',
        'Glute bridges unweighted - 12 reps with 2-second hold',
      ],
      exercises: [
        {
          id: 'ex-201',
          name: 'Goblet Squat (or Box Squat)',
          nameTamil: 'காப்லட் ஸ்குவாட் (தொடை மற்றும் இடுப்பு பயிற்சி)',
          targetMuscleGroup: 'Quadriceps, Glutes, Adductors',
          sets: 3,
          repsOrDuration: '10 - 12 reps',
          restSeconds: 60,
          difficulty: 'beginner',
          instructions: [
            'Stand with feet shoulder-width apart, toes turned slightly out.',
            'Hold dumbbell or kettlebell vertically against your chest.',
            'Hinge hips back and bend knees, driving knees outward over second toes.',
            'Descend until thighs are parallel to ground, then drive through mid-foot to stand.',
          ],
          safetyCues: [
            'Keep chest tall and do not allow knees to collapse inward.',
            'Stop above 90 degrees if knees feel sensitive.',
          ],
          modification: 'Box squat: sit down onto a dining chair and stand back up.',
          equipmentNeeded: 'Dumbbell or Bodyweight',
        },
        {
          id: 'ex-202',
          name: 'Dumbbell Romanian Deadlift (RDL)',
          nameTamil: 'ஆர்.டி.எல் (தொடையின் பின்பகுதி பயிற்சி)',
          targetMuscleGroup: 'Hamstrings, Gluteus Maximus, Lower Back',
          sets: 3,
          repsOrDuration: '10 reps',
          restSeconds: 60,
          difficulty: 'beginner',
          instructions: [
            'Stand tall with dumbbells in front of thighs, slight micro-bend in knees.',
            'Push hips back toward the wall behind you while keeping spine completely straight.',
            'Lower weights along shins until you feel a deep stretch in hamstrings.',
            'Squeeze glutes to return forward to standing position.',
          ],
          safetyCues: [
            'Do not round your lower spine; imagine pinching a pencil between shoulder blades.',
            'Movement comes from hip hinge, not bending the knees.',
          ],
          modification: 'Unweighted broomstick hinge or bodyweight good-mornings.',
          equipmentNeeded: 'Dumbbells',
        },
        {
          id: 'ex-203',
          name: 'Reverse Lunges with Balance Support',
          nameTamil: 'ரிவர்ஸ் லஞ்சஸ் (முழங்கால் இதமான பயிற்சி)',
          targetMuscleGroup: 'Quads, Glutes, Core balance',
          sets: 3,
          repsOrDuration: '8 reps per leg',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Stand tall with hands on hips or holding onto a wall for balance.',
            'Step one foot straight back, bending both knees to roughly 90 degrees.',
            'Keep front knee directly above front ankle.',
            'Push through front heel to step back to starting position.',
          ],
          safetyCues: [
            'Reverse lunges place substantially less shear stress on knees than forward lunges.',
            'Do not let front heel peel off the floor.',
          ],
          modification: 'Reduce depth of step or perform stationary split squats.',
          equipmentNeeded: 'Bodyweight',
        },
        {
          id: 'ex-204',
          name: 'Elevated Single-Leg Calf Raises',
          nameTamil: 'கால்ஃப் ரைஸ் (கெண்டைக்கால் பயிற்சி)',
          targetMuscleGroup: 'Gastrocnemius and Soleus',
          sets: 3,
          repsOrDuration: '15 reps',
          restSeconds: 30,
          difficulty: 'beginner',
          instructions: [
            'Stand on the edge of a step with balls of feet, holding a wall for balance.',
            'Lower heels slightly below step level to feel a stretch.',
            'Drive up onto balls of feet as high as possible, squeezing calves at top.',
            'Lower with control for 2 seconds.',
          ],
          safetyCues: ['Move with control without bouncing at the bottom.'],
          modification: 'Perform with both feet together on flat ground.',
          equipmentNeeded: 'Stair step or floor',
        },
      ],
      cooldown: [
        'Standing quad stretch against wall - 30s per leg',
        'Seated hamstring reach - 45s',
        'Figure-four glute stretch on floor - 30s per side',
      ],
      coachTip: 'Drive through your heels on squats and lunges to activate the glutes and protect your knees.',
    },
    {
      dayIndex: 3,
      dayName: 'Day 3: Active Recovery & Joint Decompression',
      focus: 'Spinal Mobility, Hip Openers, Light Walking',
      isRestDay: true,
      estimatedMinutes: 20,
      warmup: ['Deep diaphragmatic box breathing (4s in, 4s hold, 4s out, 4s hold) - 2 mins'],
      exercises: [],
      cooldown: ['Hydrate with 500ml water and electrolytes'],
      coachTip: 'Take a 20-30 minute gentle walk outdoors. Growth and fat loss happen during restorative sleep!',
    },
    {
      dayIndex: 4,
      dayName: 'Day 4: Upper Body Pull & Posterior Chain',
      focus: 'Lats, Rhomboids, Biceps, and Rear Delts',
      isRestDay: false,
      estimatedMinutes: 35,
      warmup: [
        'Shoulder dislocates with towel or band - 10 reps',
        'Bird-Dog stabilization - 8 reps per side',
        'Torso twists - 30 seconds',
      ],
      exercises: [
        {
          id: 'ex-401',
          name: 'Dumbbell Bent-Over Rows',
          nameTamil: 'டம்பெல் ரோயிங் (முதுகு பயிற்சி)',
          targetMuscleGroup: 'Latissimus Dorsi, Rhomboids, Biceps',
          sets: 3,
          repsOrDuration: '10 - 12 reps',
          restSeconds: 60,
          difficulty: 'beginner',
          instructions: [
            'Hinge at hips at 45 degrees, back flat, holding dumbbells hanging down.',
            'Pull elbows back past torso, driving shoulder blades together.',
            'Pause for 1 second at peak contraction.',
            'Slowly lower weights down without losing flat spinal alignment.',
          ],
          safetyCues: [
            'Do not yank with upper body momentum.',
            'Keep elbows tucked close to sides rather than flared.',
          ],
          modification: 'Chest-supported row on incline bench or resistance band pull.',
          equipmentNeeded: 'Dumbbells',
        },
        {
          id: 'ex-402',
          name: 'Resistance Band or Towel Lat Pulldowns',
          nameTamil: 'லாட் புல்டவுன்',
          targetMuscleGroup: 'Upper Back and Lats',
          sets: 3,
          repsOrDuration: '12 - 15 reps',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Hold band overhead with tension, hands wider than shoulder-width.',
            'Pull hands down and apart toward upper chest, driving elbows downward.',
            'Squeeze back muscles firmly at chest level.',
            'Control band back overhead.',
          ],
          safetyCues: ['Do not crane head forward; keep chin tucked.'],
          modification: 'Isometric towel pull-aparts.',
          equipmentNeeded: 'Resistance Band or Bath Towel',
        },
        {
          id: 'ex-403',
          name: 'Standing Alternating Dumbbell Bicep Curls',
          nameTamil: 'பைசெப் கர்ல் (முன்கை தசை)',
          targetMuscleGroup: 'Biceps Brachii',
          sets: 3,
          repsOrDuration: '10 reps each arm',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Stand tall with dumbbells by sides, palms facing in.',
            'Curl one dumbbell up while rotating palm upward toward shoulder.',
            'Squeeze bicep at the top, avoiding swinging the torso.',
            'Lower slowly and alternate to opposite arm.',
          ],
          safetyCues: ['Keep elbows glued to ribs, do not swing hips forward.'],
          modification: 'Seated curls to strictly isolate without body English.',
          equipmentNeeded: 'Dumbbells',
        },
        {
          id: 'ex-404',
          name: 'Plank with Shoulder Taps',
          nameTamil: 'பிளாங்க் ஷோல்டர் டேப் (வயிற்று உறுதி)',
          targetMuscleGroup: 'Anti-rotational Core & Shoulders',
          sets: 3,
          repsOrDuration: '10 taps total',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Begin in high push-up position with feet slightly wider than normal.',
            'Engage glutes and core to lock hips in place.',
            'Lift right hand to tap left shoulder slowly without rotating hips.',
            'Return hand down and repeat with opposite side.',
          ],
          safetyCues: ['Imagine a cup of water balancing on your lower back.'],
          modification: 'Standard static knee plank hold for 20-30 seconds.',
          equipmentNeeded: 'Mat',
        },
      ],
      cooldown: [
        'Cross-body shoulder stretch - 30s per arm',
        'Biceps wall stretch - 30s per side',
        'Cat-Cow flow - 10 gentle cycles',
      ],
      coachTip: 'Think about pulling with your elbows rather than your hands to activate the back muscles.',
    },
    {
      dayIndex: 5,
      dayName: 'Day 5: Full Body Functional HIIT & Core Burn',
      focus: 'Metabolic Conditioning, Cardio Endurance, Core',
      isRestDay: false,
      estimatedMinutes: 30,
      warmup: [
        'Jumping jacks or step-out jacks - 30 seconds',
        'High knees gentle march - 30 seconds',
        'Hip circles - 10 reps each direction',
      ],
      exercises: [
        {
          id: 'ex-501',
          name: 'Low-Impact Mountain Climbers',
          nameTamil: 'மவுண்டன் க்ளைம்பர்ஸ்',
          targetMuscleGroup: 'Cardiovascular, Core, Hip Flexors',
          sets: 3,
          repsOrDuration: '30 seconds',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Set up in high plank position with shoulders stacked over wrists.',
            'Drive one knee forward toward chest in a controlled marching tempo.',
            'Step foot back and alternate legs smoothly.',
            'Maintain steady rhythmic breathing throughout.',
          ],
          safetyCues: ['Keep hips level with shoulders; avoid bouncing up and down.'],
          modification: 'Elevate hands on a bench or wall for gentler wrist/core load.',
          equipmentNeeded: 'Bodyweight',
        },
        {
          id: 'ex-502',
          name: 'Glute Bridge with 3-Second Iso-Hold',
          nameTamil: 'க்ளூட் பிரிட்ஜ் (இடுப்பு உறுதி)',
          targetMuscleGroup: 'Glutes, Lower Back, Hamstrings',
          sets: 3,
          repsOrDuration: '12 reps',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Lie on back with knees bent and feet flat on floor, hip-width apart.',
            'Push through heels to raise hips until thighs and torso align.',
            'Squeeze glutes hard at the top for 3 full seconds.',
            'Lower hips gently back to floor.',
          ],
          safetyCues: ['Do not hyperextend lower spine at top; ribcage stays tucked.'],
          modification: 'Place a light dumbbell across hip crease for progression.',
          equipmentNeeded: 'Mat',
        },
        {
          id: 'ex-503',
          name: 'Shadow Boxing with Light Dumbbells (or Bodyweight)',
          nameTamil: 'ஷேடோ பாக்சிங் கார்டியோ',
          targetMuscleGroup: 'Shoulders, Core, Heart Rate Zone 2',
          sets: 3,
          repsOrDuration: '45 seconds',
          restSeconds: 45,
          difficulty: 'beginner',
          instructions: [
            'Adopt athletic boxer stance, hands guarding chin.',
            'Throw straight jabs, crosses, and hooks with rhythmic breathing.',
            'Rotate from balls of feet and torso to engage abdominal obliques.',
            'Maintain brisk tempo without locking out elbow joints harshly.',
          ],
          safetyCues: ['Do not snap or hyperextend elbows on punches.'],
          modification: 'Perform without weights focusing purely on footwork.',
          equipmentNeeded: 'Very light dumbbells (1-2kg) or bodyweight',
        },
      ],
      cooldown: [
        'Standing forward fold - 45 seconds',
        'Seated spinal twist - 30 seconds each side',
        'Deep resting breathing - 2 minutes',
      ],
      coachTip: 'Breathe rhythmically during cardio bursts. Inhale through nose, exhale through mouth.',
    },
    {
      dayIndex: 6,
      dayName: 'Day 6: Mobility, Core & Long Walk',
      focus: 'Active Recovery & Flexibility',
      isRestDay: true,
      estimatedMinutes: 25,
      warmup: ['Neck and wrist rolls - 2 mins'],
      exercises: [],
      cooldown: ['Full body foam rolling or light yoga stretches'],
      coachTip: 'Dedicate today to physical rejuvenation, meal prep, and recovery.',
    },
    {
      dayIndex: 7,
      dayName: 'Day 7: Complete Rest & Weekly AI Reflection',
      focus: 'Rest, Sleep, Hydration',
      isRestDay: true,
      estimatedMinutes: 10,
      warmup: [],
      exercises: [],
      cooldown: [],
      coachTip: 'Check your progress tab to generate your AI weekly performance review!',
    },
  ],
};
